import React from "react";
import { Link } from "react-router";
import "../style/info-pages.scss";

const TermsOfService = () => {
    return (
        <main className="info-page">
            <div className="info-page__container">

                <Link to="/" className="info-page__back">
                    ← Back to Readify-AI
                </Link>

                <header className="info-page__header">
                    <h1>Terms of Service</h1>
                    <p>Terms and conditions for using Readify-AI.</p>
                </header>

                <section className="info-page__content">

                    <h2>1. Using Readify-AI</h2>
                    <p>
                        Readify-AI is an AI-powered interview preparation
                        application designed to help users prepare for job
                        interviews.
                    </p>

                    <p>
                        By using the application, you agree to use it
                        responsibly and only for lawful purposes.
                    </p>

                    <h2>2. Your Account</h2>
                    <p>
                        You are responsible for providing accurate information
                        when creating your account and for keeping your account
                        credentials secure.
                    </p>

                    <h2>3. AI-Generated Content</h2>
                    <p>
                        Readify-AI uses artificial intelligence to generate
                        interview questions, preparation plans, skill gap
                        analysis, and resume content.
                    </p>

                    <p>
                        AI-generated content may contain mistakes or
                        inaccuracies. You should review generated content and
                        use your own judgment before relying on it.
                    </p>

                    <h2>4. Resume and Job Information</h2>
                    <p>
                        You are responsible for the information you provide,
                        including resumes, job descriptions, and personal
                        descriptions.
                    </p>

                    <p>
                        Do not upload information that you do not have the
                        right to share with the application.
                    </p>

                    <h2>5. Acceptable Use</h2>
                    <p>
                        You agree not to misuse the application, attempt to
                        gain unauthorized access to other accounts, interfere
                        with the application's operation, or use the service
                        for unlawful activities.
                    </p>

                    <h2>6. Service Availability</h2>
                    <p>
                        Readify-AI may be updated, modified, temporarily
                        unavailable, or discontinued as the project evolves.
                        We do not guarantee uninterrupted availability of the
                        application.
                    </p>

                    <h2>7. Limitation of Responsibility</h2>
                    <p>
                        Readify-AI is intended as a preparation and assistance
                        tool. It does not guarantee employment, interview
                        success, or the accuracy of every recommendation
                        generated by the AI.
                    </p>

                    <h2>8. Changes to These Terms</h2>
                    <p>
                        These Terms of Service may be updated as Readify-AI
                        develops. Continued use of the application after
                        changes means you accept the updated terms.
                    </p>

                    <h2>9. Contact</h2>
                    <p>
                        If you have questions about these terms, please use
                        the Help Center or contact the project administrator.
                    </p>

                </section>

                <footer className="info-page__footer">
                    <Link to="/privacy-policy">Privacy Policy</Link>
                    <Link to="/help">Help Center</Link>
                </footer>

            </div>
        </main>
    );
};

export default TermsOfService;